### Data preparation

* Check if the missing values are presented in the features.
* If there are missing values:
    * For categorical features, replace them with 'NA'
    * For numerical features, replace with with 0.0

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("course_lead_scoring_2026.csv")
df

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1
...,...,...,...,...,...,...,...,...,...
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [2]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [3]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [4]:
categorical_columns = list(df.dtypes[df.dtypes == 'str'].index)
numerical_columns=["number_of_courses_viewed","annual_income","interaction_count","lead_score","converted" ]

for c in categorical_columns:
    
    df[c] = df[c].fillna('NA')

len(numerical_columns)+len(categorical_columns)

9

In [5]:
df.isnull().sum()

lead_source                   0
industry                      0
employment_status             0
location                      0
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [6]:
df['annual_income'] = df['annual_income'].fillna(0.0)
df['lead_score'] = df['lead_score'].fillna(0.0)

df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

### Question 1

What is the most frequent observation (mode) for the column `industry`?

- `NA`
- `technology`
- `healthcare`
- `retail`

In [7]:
df.industry.mode()

0    technology
Name: industry, dtype: str

#### Answer Question 1: technology

### Question 2

Create the [correlation matrix](https://www.google.com/search?q=correlation+matrix) for the numerical features of your dataset.
In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

- `interaction_count` and `lead_score`
- `number_of_courses_viewed` and `lead_score`
- `number_of_courses_viewed` and `interaction_count`
- `annual_income` and `interaction_count`

Only consider the pairs above when answering this question.

In [8]:
numerical_columns=["number_of_courses_viewed","annual_income","interaction_count","lead_score" ]

# Select numerical features from the dataset
numerical_features = df[numerical_columns]

# Compute the correlation matrix
correlation_matrix = numerical_features.corr()

# Display the correlation matrix
print("Correlation matrix:")
correlation_matrix

Correlation matrix:

,number_of_courses_viewed,annual_income,interaction_count,lead_score
number_of_courses_viewed,1.000000,0.161300,0.721609,0.757204
annual_income,0.161300,1.000000,0.122842,0.229496
interaction_count,0.721609,0.122842,1.000000,0.915746
lead_score,0.757204,0.229496,0.915746,1.000000

In [9]:
print(correlation_matrix.loc["interaction_count","lead_score"])
print(correlation_matrix.loc ["number_of_courses_viewed","lead_score"])
print(correlation_matrix.loc["number_of_courses_viewed","interaction_count"])
print(correlation_matrix.loc["annual_income","interaction_count"])

0.9157457980418697
0.7572042392104886
0.7216090038937035
0.12284235135955959

#### Answer Question 2: interaction_count and lead score


### Question 3

- Calculate the mutual information score between `converted` and other categorical variables in the dataset. Use the training set only.
- Round the scores to 2 decimals using `round(score, 2)`.

Which of these variables has the biggest mutual information score?

- `industry`
- `location`
- `lead_source`
- `employment_status`

In [10]:
from sklearn.model_selection import train_test_split
df = df.rename(columns={"converted": "y"})
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=42
)
df_train.drop(columns=['y']).shape

(3000, 8)

In [11]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd

# Select categorical features from the training set
categorical_features = ['industry', 'location', 'lead_score', 'employment_status']
X_train_categorical = df_train[categorical_features]

# One-hot encode categorical variables
X_train_encoded = pd.get_dummies(X_train_categorical, drop_first=True)
X_train_encoded
# Calculate the mutual information scores

,lead_score,industry_education,industry_finance,industry_healthcare,industry_manufacturing,industry_retail,industry_technology,location_africa,location_asia,location_europe,location_north_america,location_south_america,employment_status_employed,employment_status_self_employed,employment_status_student,employment_status_unemployed
4702,0.37,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False
2155,0.09,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False
289,0.55,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False
1822,0.45,False,True,False,False,False,False,False,False,False,True,False,True,False,False,False
3442,0.00,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3200,0.29,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False
617,0.30,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False
1992,0.58,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False
3301,0.03,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False
3687,0.34,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False

In [12]:

mi_scores = mutual_info_classif(X_train_encoded, df_train["y"], random_state=42)

# Create a DataFrame to display the scores alongside the features
mi_scores_df = pd.DataFrame({
    'Feature': X_train_encoded.columns,
    'Mutual Information Score': mi_scores
})
mi_scores_df

                            Feature  Mutual Information Score
0                        lead_score                  0.131630
1                industry_education                  0.000000
2                  industry_finance                  0.016201
3               industry_healthcare                  0.000000
4            industry_manufacturing                  0.001295
5                   industry_retail                  0.000000
6               industry_technology                  0.008729
7                   location_africa                  0.005492
8                     location_asia                  0.000000
9                   location_europe                  0.000000
10           location_north_america                  0.004387
11           location_south_america                  0.000000
12       employment_status_employed                  0.022088
13  employment_status_self_employed                  0.000000
14        employment_status_student                  0.014954
15     employment_status_unemployed                  0.013542

In [13]:
# Extract the original categorical variable names by splitting on the first underscore
mi_scores_df['Variable'] = mi_scores_df['Feature'].str.split('_').str[0]
mi_scores_df

                            Feature  Mutual Information Score    Variable
0                        lead_score                  0.131630        lead
1                industry_education                  0.000000    industry
2                  industry_finance                  0.016201    industry
3               industry_healthcare                  0.000000    industry
4            industry_manufacturing                  0.001295    industry
5                   industry_retail                  0.000000    industry
6               industry_technology                  0.008729    industry
7                   location_africa                  0.005492    location
8                     location_asia                  0.000000    location
9                   location_europe                  0.000000    location
10           location_north_america                  0.004387    location
11           location_south_america                  0.000000    location
12       employment_status_employed                  0.022088  employment
13  employment_status_self_employed                  0.000000  employment
14        employment_status_student                  0.014954  employment
15     employment_status_unemployed                  0.013542  employment

In [14]:
# Group by the original categorical variables and sum their MI scores
mi_scores_summed = mi_scores_df.groupby('Variable')['Mutual Information Score'].sum()

# Round the scores to 2 decimals
mi_scores_summed = mi_scores_summed.round(2)

# Sort the scores in descending order to find the variable with the highest MI score
mi_scores_summed_sorted = mi_scores_summed.sort_values(ascending=False)

# Display the mutual information scores
print("Mutual Information Scores:")
print(mi_scores_summed_sorted)

# Identify the variable with the highest mutual information score
highest_mi_variable = mi_scores_summed_sorted.idxmax()
highest_mi_score = mi_scores_summed_sorted.max()

print(f"\nThe variable with the highest mutual information score is '{highest_mi_variable}' with a score of {highest_mi_score}.")

Mutual Information Scores:
Variable
lead          0.13
employment    0.05
industry      0.03
location      0.01
Name: Mutual Information Score, dtype: float64

The variable with the highest mutual information score is 'lead' with a score of 0.13.

### Question 4

- Now let's train a logistic regression.
- Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
- Fit the model on the training dataset.
  - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
  - `model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)`
- Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

What accuracy did you get?

- 0.55
- 0.65
- 0.75
- 0.85

In [15]:
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)
len(df_train), len(df_val), len(df_test)

(3000, 1000, 1000)

In [16]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
y_train = df_train.y.values
y_test = df_test.y.values
y_val = df_test.y.values

del df_train['y']
del df_test['y']
del df_val['y']
df_full_train.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
y                           0
dtype: int64

In [17]:
df_full_train.y.value_counts()

y
1    2315
0    1685
Name: count, dtype: int64

In [18]:
df_full_train.y.value_counts(normalize=True)

y
1    0.57875
0    0.42125
Name: proportion, dtype: float64

In [19]:
df_full_train.y.mean()

np.float64(0.57875)

In [20]:
df_full_train.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
y                             int64
dtype: object

In [21]:
df_full_train

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,y
1233,paid_ads,technology,student,europe,38757.0,0,0,0.15,0
1056,paid_ads,healthcare,self_employed,north_america,56516.0,2,6,0.59,1
1686,paid_ads,retail,employed,NA,54963.0,1,0,0.13,0
187,social_media,retail,self_employed,NA,26237.0,1,5,0.46,0
3840,organic_search,retail,student,north_america,21992.0,3,6,0.70,1
...,...,...,...,...,...,...,...,...,...
2895,paid_ads,manufacturing,NA,north_america,66121.0,1,1,0.20,0
2763,paid_ads,manufacturing,employed,north_america,60720.0,4,6,0.69,1
905,NA,manufacturing,NA,NA,49820.0,2,3,0.44,0
3980,organic_search,manufacturing,self_employed,north_america,52228.0,3,5,0.50,0
235,paid_ads,retail,employed,asia,25824.0,1,4,0.41,0

In [22]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']
df_full_train[categorical].nunique()

lead_source          6
industry             7
employment_status    5
location             6
dtype: int64

In [23]:
numerical=["number_of_courses_viewed","annual_income","interaction_count","lead_score" ]
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
categorical = ['lead_source', 'industry', 'employment_status', 'location']
train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
# solver='lbfgs' is the default solver in newer version of sklearn
# for older versions, you need to specify it explicitly
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [24]:
model.intercept_[0],model.coef_[0].round(3)

(np.float64(-0.09288149430633613),
 array([-0.   , -0.001,  0.033, -0.023, -0.055, -0.047, -0.004, -0.025,
        -0.012, -0.024, -0.009, -0.032,  0.012,  0.252,  0.019, -0.002,
        -0.041,  0.013, -0.065,  0.027, -0.025, -0.005, -0.02 , -0.015,
        -0.01 , -0.022, -0.021,  0.105]))

In [25]:
y_pred = model.predict_proba(X_val)[:, 1]
output_model=(y_pred >= 0.5)
(y_val == output_model).mean()

np.float64(0.541)

#### Answer Question 4: 0.541

### Question 5

- Let's find the least useful feature using the _feature elimination_ technique.
- Train a model using the same features and parameters as in Q4 (without rounding).
- Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
- For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

Which of following feature has the smallest difference?

- `'lead_source'`
- `'number_of_courses_viewed'`
- `'interaction_count'`

> **Note**: The difference doesn't have to be positive.

In [26]:
original_accuracy=0.541
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)

for feature  in ['lead_score', 'number_of_courses_viewed', 'interaction_count']:
    categorical_num = categorical + numerical
    categorical_num.remove(feature)
    train_dict = df_train[categorical_num].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)
    val_dict = df_val[categorical_num].to_dict(orient='records')
    X_val = dv.transform(val_dict)
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    output_model=(y_pred >= 0.5)
    print(feature, f"--->Difference={original_accuracy-(y_val == output_model).mean()}")

lead_score --->Difference=0.0
number_of_courses_viewed --->Difference=-0.0020000000000000018
interaction_count --->Difference=-0.027999999999999914

#### Answer Question 5: interaction_count

### Question 6

- Now let's train a regularized logistic regression.
- Let's try the following values of the parameter `C`: `[0.000001, 0.00001, 0.0001, 0.001]`.
- Train models using all the features as in Q4.
- Calculate the accuracy on the validation dataset and round it to 3 decimal digits.

Which of these `C` leads to the best accuracy on the validation set?

- 0.000001
- 0.00001
- 0.0001
- 0.001

In [27]:
for C in [0.000001, 0.00001, 0.0001, 0.001]:
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    output_model=(y_pred >= 0.5)
    print(f"C={C}--->Accuracy={(y_val == output_model).mean().round(3)}")

C=1e-06--->Accuracy=0.569
C=1e-05--->Accuracy=0.569
C=0.0001--->Accuracy=0.569
C=0.001--->Accuracy=0.569

#### Answer Question 6: C=0.000001